### ISSUE TITLE
what is the license of this repository?

### ISSUE THREAD

**Issue by vvakame** [apollographql/federation-demo#12]
same as https://github.com/apollographql/apollo-server/blob/master/LICENSE ? 🤔

**Comment by vvakame** [comment]
@jbaxleyiii Hi! could you take a look?

**Comment by nitin302** [comment]
@martijnwalraven @abernix is update?

**Comment by abernix** [comment]
I've added an MIT license to this repository and otherwise brought it up to date with latest dependencies and patterns.  Thanks for the ping!
